Finished assignment 3. Waiting for approval
andrefnb/faast_assignment1 pull request #4
Opened 2023-04-03 15:33 UTC by andrefnb

2023-04-11 14:47 UTC, MrCordeiro requested changes

2023-04-11 14:47 UTC, MrCordeiro commented on .github/workflows/test.yml
> +        pylint life_expectancy.data_cleaning
```suggestion
        pylint life_expectancy
```

Incluira tamb]em os testes.

2023-04-11 14:47 UTC, MrCordeiro commented on .vscode/settings.json
Não boa idea colocar esse fecheiro no commit.

2023-04-11 14:47 UTC, MrCordeiro commented on life_expectancy/main.py
> +FILE_PATH = f"{PROJECT_DIR}/data/eu_life_expectancy_raw.tsv"
```suggestion
FILE_PATH = PROJECT_DIR / "data" / "eu_life_expectancy_raw.tsv"
```

2023-04-11 14:47 UTC, MrCordeiro commented on life_expectancy/data_loading.py
> +def load_data(file_path: str, sep: str = ",") -> pd.DataFrame:
```suggestion
def load_data(file_path: Path | str, sep: str = ",") -> pd.DataFrame:
```

2023-04-11 14:47 UTC, MrCordeiro commented on life_expectancy/data_loading.py
> +def load_data(file_path: str, sep: str = ",") -> pd.DataFrame:
Acho para Python < 3.10, usas:

from typings import Union

Union[str, Path]

2023-04-11 14:47 UTC, MrCordeiro commented on life_expectancy/tests/conftest.py
**Comment** Podemos deletar este setup se tudo estiver ok

2023-04-11 14:47 UTC, MrCordeiro commented on life_expectancy/tests/test_cleaning.py
Criar um module de testes para cada modulo do projeto

2023-04-11 14:47 UTC, MrCordeiro commented on life_expectancy/tests/test_cleaning.py
> +@mock.patch("pandas.DataFrame.to_csv")
```suggestion
@mock.patch("life_expectancy.data_loading.pd.DataFrame.to_csv")
```

2023-04-11 14:47 UTC, MrCordeiro commented on life_expectancy/tests/test_cleaning.py
> +def test_main(pt_life_expectancy_expected):
Faltam os mocks para ler (para consumir teu fixture) e gravar dataframe.

2023-04-11 14:47 UTC, MrCordeiro commented on life_expectancy/tests/test_cleaning.py
> +def test_main(pt_life_expectancy_expected):
```python
@patch(life_expactancy.main.read_data)
@patch(save)
def test_xxxx (mock_save, mock_read, ...)

   # Para que o mock retorne a minha fixture
   mock_read.return_value = minha_fixture
   
   # Para que o mock realize alguma ação ao ser chamado
   mock_save.side_effect = print("I'm saving")
```

2023-04-14 13:50 UTC, filipacarreira reviewed
Great job André! Congrats 🥳

2023-04-14 13:50 UTC, filipacarreira commented on life_expectancy/main.py
> +SAVE_PATH = "life_expectancy/data/pt_life_expectancy.csv"
this variable can't also use the PROJECT_DIR variable?
Like: `SAVE_PATH = PROJECT_DIR / data / pt_life_expectancy.csv`

2023-04-14 13:50 UTC, filipacarreira commented on life_expectancy/tests/test_cleaning.py
> +FILE_PATH = f"{PROJECT_DIR}/data/eu_life_expectancy_raw.tsv"
Is the same suggestion Fernando did before, changing it to
`FILE_PATH = PROJECT_DIR / "data" / "eu_life_expectancy_raw.tsv"`

2023-04-18 11:46 UTC, MrCordeiro requested changes

2023-04-18 11:46 UTC, MrCordeiro commented on life_expectancy/tests/test_loading.py
> +    dataframe = load_data(FILE_PATH, "\t")
Aqui deverias estar a consumir das fixtures, não do directorio `data`

2023-04-18 14:12 UTC, MrCordeiro approved these changes

2023-04-18 14:17 UTC, merged